server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO
  appenders:
    - type: console

mongo:
  uri: "mongodb+srv://shubham:1234567890@cluster0.ppm7bwf.mongodb.net/assignmentDB?retryWrites=true&w=majority"
  database: "assignmentDB"
